### ISSUE TITLE
Things to do before public release

### ISSUE THREAD

**Issue by SteveBronder** [WardBrian/tinystan#20]
Just making a running issue we can add to for things that need done before a public release. Feel free to edit this post directly to add things

## Overall

- [ ] Docs / doxygen for the C code

## R Package

- [ ] Docs for all public functions
- [ ] Vignette for usage
- [ ] tinystan-tools companion package?
- [ ] Add methods for running loo etc. with tinystan model
- [ ] Verbose checking of inputs for all the algorithms
- [ ] Harden compile functions
- [ ] Decide on output format

For the inputs and compile functions we can steal a lot from cmdstanr. For the output, I'm thinking about just returning a small environment called `tinystan-fit` that has
  - [ ] return samples as rvars 
  - [ ] S3 functions defined to extract rvars to the environment
  - [ ] S3 functions for calling loo etc on the fit? Since we want to keep things simple I'm not sure that's within scope

**Comment by WardBrian** [comment]
The file `TODO.md` has some other things, but they're mostly coarse-grained versions of what you mention here. For documentation I plan on more or less copying the website config from bridgestan once we have doc comments in the source.

The small `tinystan-fit` sounds pretty much like what I have in Python, and sounds useful.

**Comment by SteveBronder** [comment]
Word! I'll close this and add these things to the TODO.md
